---
deployment:
  tasks:
    - export DEPLOYPATH=/home/monterab/public_html/
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R image $DEPLOYPATH
    - /bin/cp -R video $DEPLOYPATH
    - /bin/cp aboutUs.js $DEPLOYPATH
    - /bin/cp fonts.css $DEPLOYPATH
    - /bin/cp gallery.js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp service.js $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - export REPOPATH=/home/monterab/repositories/*
      - export SITEPATH=/home/yourdoma/public_html/
      - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del